[project]
name = "awesome-dev-mcp"
version = "0.1.0"
description = "An awesome Model Context Protocol (MCP) server for development tools and utilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.3",
]
